controllers:
    resource: ../../src/Controller/
    type: annotation

user_controller:
    resource: ../../src/Components/User/Communication/
    type: annotation

exam_controller:
    resource: ../../src/Components/Exam/Communication/
    type: annotation

question_controller:
    resource: ../../src/Components/Answer/Communication/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation